name: Webshop development CI/CD

on:
  push:
    branches:
      - dev

jobs:
  docker-build-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          ls
          cd ElectronicsWebshop
          docker build -f Dockerfile.dev -t leevil/webshop-dev-image:latest .
          docker image prune -f
          cd ..
          rm -rf ElectronicsWebshop

  deploy:
    needs: docker-build-push
    runs-on: self-hosted

    steps:
      - name: Start container
        run: |
          docker rm -f webshop-dev-container || true
          docker run -d --restart unless-stopped --env-file /home/leevi/.env --name webshop-dev-container -p 1234:1234 -v /home/leevi/dev-pictures:/app/server/uploads leevil/webshop-dev-image:latest
