name: Webshop development CI/CD

on:
  push:
    branches:
      - dev

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.dev -t webshop-dev-image .

  deploy:
    needs: docker-build
    runs-on: self-hosted

    steps:
      - name: Deploy Docker image
        run: |
          docker rm -f webshop-dev-container || true
          docker run -d --restart unless-stopped --env-file /home/leevi/.env --name webshop-dev-container -p 1234:1234 -v /home/leevi/dev-pictures:/app/server/uploads webshop-dev-image
          docker image prune -f
