name: Webshop development CI/CD

on:
  push:
    branches:
      - dev

jobs:
  docker-build-push:
    runs-on: self-hosted

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            git clone git@github.com:LeeviLautanen/ElectronicsWebshop.git
            cd ElectronicsWebshop
            docker build -f Dockerfile.dev -t leevil/webshop-dev-image:latest .
            docker push leevil/webshop-dev-image:latest
            docker image prune -f
            cd ..
            rm -rf ElectronicsWebshop
          '

  deploy:
    needs: docker-build-push
    runs-on: self-hosted

    steps:
      - name: SSH into server and deploy Docker image
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          docker pull leevil/webshop-dev-image:latest;
          docker stop webshop-dev-container || true;
          docker rm webshop-dev-container || true;
          docker run -d --restart unless-stopped --env-file .env --name webshop-dev-container -p 1234:1234 -v dev-product-pictures:/app/server/uploads leevil/webshop-dev-image:latest;
          docker image prune -f"
