name: Webshop production CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.prod -t leevil/webshop-prod-image:latest .
          docker push leevil/webshop-prod-image:latest
          docker image prune -f

  deploy:
    needs: docker-build-push
    runs-on: self-hosted

    steps:
      - name: Connect SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SSH into server and deploy Docker image
        run: |
          ssh -p 2222 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          docker pull leevil/webshop-prod-image:latest;
          docker stop webshop-prod-container || true;
          docker rm webshop-prod-container || true;
          docker run -d --restart unless-stopped --env-file .env --name webshop-prod-container -p 2024:2024 -v prod-product-pictures:/app/server/uploads leevil/webshop-prod-image:latest;
          docker image prune -f"
