name: Webshop production CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.dev -t webshop-prod-image .

  deploy:
    needs: docker-build-push
    runs-on: self-hosted

    steps:
      - name: Deploy Docker image
        run: |
          docker rm -f webshop-prod-container || true
          docker run -d --restart unless-stopped --env-file /home/leevi/.env --name webshop-prod-container -p 2024:2024 -v /home/leevi/prod-pictures:/app/server/uploads webshop-prod-image:latest;
          docker image prune -f"
